### ISSUE TITLE
请教一下，该框架下可以实现变量声明的时候初始化吗

### ISSUE THREAD

**Issue by c-learnc** [tch0/JustAToyCCompiler#2]

**Comment by tch0** [comment]
- 这个东西就是一个玩具，怎么简单怎么来，是从C语言中取的最容易实现的能单趟解析的子集来实现的。
- 要部分实现初始化那肯定是可以的，问题是能实现到什么程度。
- 如果不能相对比较完备的实现，那还不如不实现。

现在的框架下要实现初始化要解决几个问题：
- 标准C要求全局变量的初始化器是常量，比如`1+1`这种常量表达式，编译后常量表达式的值已经被计算出来了。但现在因为没有实现编译期计算，编译器就不知道`1+1`是常量，就需要生成指令在运行时去计算，这些指令需要在main之前执行（现在是解析完直接执行main，那就需要将这些初始化解析到一个初始化函数比如叫init里面去，然后调用main之前去调init）。或者去实现编译期计算（并不简单）。
- 局部变量的初始化倒是总是可以通过变换代码实现：
```C
int a = 1;
int b = a + 1;
// convert to
int a;
int b;
a = 1;
b = a + 1;
```
- 可以在源码层面做也可以指令层面做，在解析到`int b = a + 1;`前你需要将`a = 1`这个信息存起来，要么源码形式要么指令形式，然后在声明解析完后再来解析存起来的源码或者将存起来的指令加进去，现在并没有提供这两种机制，需要自己加。
- 结构体联合体初始化器，这个要完善支持是很复杂的。

现在的代码仅仅是取的一个能用的功能完备的子集，没有实现的东西太多了，初始化只是其中一个，但基本的功能你都可以通过其他途径实做到。这里只是为了简单写一个只要有C语言基础谁都能读懂的编译器，越简单越好，搞复杂了反而不利于阅读。比如结构体赋值都不支持，但可以用memcpy来拷贝。

**Comment by c-learnc** [comment]
感谢楼主，我也想了一些“不太完善的实现方法”，思路和楼主说的差不多。
另外这种项目，既易读，又能引发思考，对于我这种初学者的确受益很多。
